### ISSUE TITLE
Port Laravel app into FastAPI

### ISSUE THREAD

**Issue by faierbol** [sz3lbi/classifieds_service_backend#6]
HI, just a small question, do you think that it would be possible to port this laravel app https://github.com/marketplacekit/marketplacekit into fastapi?
Basically creating something similar but in fastapi.
Thanks in advanced for your response :)

**Comment by sz3lbi** [comment]
Hello,  
Yes, it is possible for sure. The thing is that with PHP you can create back-end as well as front-end. FastAPI offers only the back-end side of the application, so the front-end should be created separately with some library like React or framework like Vue. Then, you would have to generate a TypeScript client for your API (with some tool like Orval or OpenAPI Generator) and connect them together.   
But you will be able to recreate the app and offer the same functionality to your users.

**Comment by faierbol** [comment]
Thank you for your answer! So do you think that you can build something similar?

**Comment by sz3lbi** [comment]
I think I would be able to, but it would cost me a lot of time. I have some other projects pending, so I am not able to tell when I would find a free time spot to implement it. Probably not soon.

**Comment by faierbol** [comment]
Hi @sz3lbi i am willing to pay :)

**Comment by sz3lbi** [comment]
I don't know how much I would be capable of this considering probably not-so-long deadline, but you can contact me at szelbi@szelbi.ovh to discuss the details.
